---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-access-operator
  labels:
    app: strimzi-access-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-access-operator
      strimzi.io/kind: access-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: strimzi-access-operator
        strimzi.io/kind: access-operator
    spec:
      serviceAccountName: strimzi-access-operator
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- with .Values.image.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
      containers:
        - name: access-operator
          image: {{ .Values.image.registry }}/{{ .Values.image.repository}}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/access_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
